const baseColors = (theme) => {
  const { palette, tokenColors: tokenPalette } = theme;

  return {
    colors: {
      'activityBar.activeBackground': `${palette.accent1}10`,
      'activityBar.activeBorder': `${palette.accent2}80`,
      'activityBar.background': palette.bgDarkest,
      'activityBar.foreground': palette.fgBright,
      'activityBar.inactiveForeground': palette.fgMuted,
      'activityBarBadge.background': palette.accent2,
      'activityBarBadge.foreground': palette.fgBright,

      'badge.background': palette.bgHighlight,
      'badge.foreground': palette.fgBright,

      'breadcrumb.activeSelectionForeground': palette.fgBright,
      'breadcrumb.background': palette.bgDarkest,
      'breadcrumb.focusForeground': palette.fgBright,
      'breadcrumb.foreground': palette.fgMuted,
      'breadcrumbPicker.background': palette.bgDarkest,

      'button.background': palette.bgHighlight,
      'button.foreground': palette.fgBright,

      contrastBorder: palette.bgDarkest,
      'debugToolBar.background': palette.bgDarkest,
      'diffEditor.insertedTextBackground': `${palette.accent4}20`,
      'diffEditor.removedTextBackground': `${palette.accent12}50`,

      // Dropdown
      'dropdown.background': palette.bgDarkest,
      'dropdown.border': palette.bgDarkest,
      'dropdown.foreground': palette.fgBright,

      // Editor
      'editor.background': palette.bgDark,
      'editor.findMatchBackground': `${palette.accent9}80`,
      'editor.findMatchHighlightBackground': `${palette.fgBright}40`,
      'editor.findRangeHighlightBackground': `${palette.bgHighlight}75`,
      'editor.foreground': palette.fgBright,
      'editor.hoverHighlightBackground': palette.bgDarkest,
      'editor.lineHighlightBorder': palette.bgHighlight,
      'editor.rangeHighlightBackground': `${palette.accent1}15`,
      'editor.selectionBackground': palette.bgHighlight,
      'editor.selectionHighlightBackground': palette.bgMedium,
      'editor.snippetFinalTabstopHighlightBackground': palette.bgDark,
      'editor.snippetFinalTabstopHighlightBorder': palette.accent4,
      'editor.snippetTabstopHighlightBackground': palette.bgDark,
      'editor.snippetTabstopHighlightBorder': palette.fgMuted,
      'editor.wordHighlightBackground': `${palette.accent6}50`,
      'editor.wordHighlightStrongBackground': `${palette.accent4}50`,

      'editorCodeLens.foreground': palette.fgMuted,
      'editorError.foreground': palette.accent12,
      'editorGroup.border': palette.accent1,
      'editorGroup.dropBackground': `${palette.bgHighlight}70`,
      'editorGroupHeader.tabsBackground': palette.bgDarkest,
      'editorGutter.addedBackground': `${palette.accent4}80`,
      'editorGutter.deletedBackground': `${palette.accent12}80`,
      'editorGutter.modifiedBackground': `${palette.accent6}80`,
      'editorHoverWidget.background': palette.bgDark,
      'editorHoverWidget.border': palette.fgMuted,
      'editorIndentGuide.activeBackground': `${palette.fgBright}45`,
      'editorIndentGuide.background': palette.bgMedium,
      'editorLineNumber.foreground': palette.fgMuted,
      'editorLink.activeForeground': palette.accent6,
      'editorMarkerNavigation.background': palette.bgDarkest,
      'editorOverviewRuler.addedForeground': `${palette.accent4}80`,
      'editorOverviewRuler.border': palette.bgDarkest,
      'editorOverviewRuler.currentContentForeground': palette.accent4,
      'editorOverviewRuler.deletedForeground': `${palette.accent12}80`,
      'editorOverviewRuler.errorForeground': `${palette.accent12}80`,
      'editorOverviewRuler.incomingContentForeground': palette.accent1,
      'editorOverviewRuler.infoForeground': `${palette.accent6}80`,
      'editorOverviewRuler.modifiedForeground': `${palette.accent6}80`,
      'editorOverviewRuler.selectionHighlightForeground': palette.accent9,
      'editorOverviewRuler.warningForeground': `${palette.accent9}80`,
      'editorOverviewRuler.wordHighlightForeground': palette.accent6,
      'editorOverviewRuler.wordHighlightStrongForeground': palette.accent4,
      'editorRuler.foreground': palette.bgMedium,
      'editorSuggestWidget.background': palette.bgDarkest,
      'editorSuggestWidget.foreground': palette.fgBright,
      'editorSuggestWidget.selectedBackground': palette.bgHighlight,
      'editorWarning.foreground': palette.accent6,
      'editorWhitespace.foreground': palette.bgMedium,
      'editorWidget.background': palette.bgDarkest,

      errorForeground: palette.neutralGrey,
      'extensionButton.prominentBackground': `${palette.accent4}90`,
      'extensionButton.prominentForeground': palette.fgBright,
      'extensionButton.prominentHoverBackground': `${palette.accent4}60`,
      focusBorder: palette.fgMuted,
      foreground: palette.fgBright,

      'gitDecoration.conflictingResourceForeground': palette.accent9,
      'gitDecoration.deletedResourceForeground': palette.accent12,
      'gitDecoration.ignoredResourceForeground': palette.fgMuted,
      'gitDecoration.modifiedResourceForeground': palette.accent6,
      'gitDecoration.untrackedResourceForeground': palette.accent4,

      'input.background': palette.bgDark,
      'input.border': palette.bgDarkest,
      'input.foreground': palette.fgBright,

      'input.placeholderForeground': palette.fgMuted,
      'inputOption.activeBorder': palette.accent1,
      'inputValidation.errorBorder': palette.accent12,
      'inputValidation.infoBorder': palette.accent2,
      'inputValidation.warningBorder': palette.accent9,

      'list.activeSelectionBackground': palette.bgHighlight,
      'list.activeSelectionForeground': palette.fgBright,
      'list.dropBackground': palette.bgHighlight,
      'list.errorForeground': palette.neutralGrey,
      'list.focusBackground': `${palette.bgHighlight}75`,
      'list.highlightForeground': palette.accent6,
      'list.hoverBackground': `${palette.bgHighlight}75`,
      'list.inactiveSelectionBackground': `${palette.bgHighlight}75`,
      'list.warningForeground': palette.accent9,
      'list.filterMatchBackground': `${palette.fgBright}40`,
      'list.invalidItemForeground': '#b89500',
      'list.deemphasizedForeground': `${palette.accent2}40`,

      'listFilterWidget.background': palette.bgDarkest,
      'listFilterWidget.noMatchesOutline': palette.accent12,
      'listFilterWidget.outline': palette.bgMedium,

      'merge.currentHeaderBackground': `${palette.accent4}90`,
      'merge.incomingHeaderBackground': `${palette.accent1}90`,

      'panel.background': palette.bgDark,
      'panel.border': palette.accent1,
      'panelTitle.activeBorder': palette.accent2,
      'panelTitle.activeForeground': palette.fgBright,
      'panelTitle.inactiveForeground': palette.fgMuted,

      'peekView.border': palette.bgHighlight,
      'peekViewEditor.background': palette.bgDark,
      'peekViewEditor.matchHighlightBackground': `${palette.accent10}80`,
      'peekViewResult.background': palette.bgDarkest,
      'peekViewResult.fileForeground': palette.fgBright,
      'peekViewResult.lineForeground': palette.fgBright,
      'peekViewResult.matchHighlightBackground': `${palette.accent10}80`,
      'peekViewResult.selectionBackground': palette.bgHighlight,
      'peekViewResult.selectionForeground': palette.fgBright,
      'peekViewTitle.background': palette.bgDarkest,
      'peekViewTitleDescription.foreground': palette.fgMuted,
      'peekViewTitleLabel.foreground': palette.fgBright,
      'pickerGroup.border': palette.accent1,
      'pickerGroup.foreground': palette.accent6,
      'progressBar.background': palette.accent2,
      'selection.background': palette.accent1,

      'settings.checkboxBackground': palette.bgDarkest,
      'settings.checkboxBorder': palette.bgDarkest,
      'settings.checkboxForeground': palette.fgBright,
      'settings.dropdownBackground': palette.bgDarkest,
      'settings.dropdownBorder': palette.bgDarkest,
      'settings.dropdownForeground': palette.fgBright,
      'settings.headerForeground': palette.fgBright,
      'settings.modifiedItemIndicator': palette.accent9,
      'settings.numberInputBackground': palette.bgDarkest,
      'settings.numberInputBorder': palette.bgDarkest,
      'settings.numberInputForeground': palette.fgBright,
      'settings.textInputBackground': palette.bgDarkest,
      'settings.textInputBorder': palette.bgDarkest,
      'settings.textInputForeground': palette.fgBright,

      'sideBar.background': palette.bgDarkest,
      'sideBarSectionHeader.background': palette.bgDarkest,
      'sideBarSectionHeader.border': palette.bgDarkest,
      'sideBarTitle.foreground': palette.fgBright,

      'statusBar.background': palette.bgDarkest,
      'statusBar.debuggingBackground': palette.accent12,
      'statusBar.debuggingForeground': palette.bgDarkest,
      'statusBar.foreground': palette.fgBright,
      'statusBar.noFolderBackground': palette.bgDarkest,
      'statusBar.noFolderForeground': palette.fgBright,
      'statusBarItem.prominentBackground': palette.accent12,
      'statusBarItem.prominentHoverBackground': palette.accent9,
      'statusBarItem.remoteBackground': palette.accent1,
      'statusBarItem.remoteForeground': palette.fgBright,

      'tab.activeBackground': palette.bgDark,
      'tab.activeBorder': `${palette.accent2}80`,
      'tab.activeForeground': palette.fgBright,
      'tab.border': palette.bgDarkest,
      'tab.inactiveBackground': palette.bgDarkest,
      'tab.inactiveForeground': palette.fgMuted,

      'terminal.ansiBlack': palette.bgDarkest,
      'terminal.ansiBlue': palette.accent1,
      'terminal.ansiBrightBlack': palette.fgMuted,
      'terminal.ansiBrightBlue': '#d6acff',
      'terminal.ansiBrightCyan': '#a4ffff',
      'terminal.ansiBrightGreen': '#69ff94',
      'terminal.ansiBrightMagenta': '#ff92df',
      'terminal.ansiBrightRed': '#ff6e6e',
      'terminal.ansiBrightWhite': '#ffffff',
      'terminal.ansiBrightYellow': '#ffffa5',
      'terminal.ansiCyan': palette.accent6,
      'terminal.ansiGreen': palette.accent4,
      'terminal.ansiMagenta': palette.accent2,
      'terminal.ansiRed': palette.accent12,
      'terminal.ansiWhite': palette.fgBright,
      'terminal.ansiYellow': palette.accent10,
      'terminal.background': palette.bgDark,
      'terminal.foreground': palette.fgBright,

      'titleBar.activeBackground': palette.bgDarkest,
      'titleBar.activeForeground': palette.fgBright,
      'titleBar.inactiveBackground': palette.bgDarkest,
      'titleBar.inactiveForeground': palette.fgMuted,

      'walkThrough.embeddedEditorBackground': palette.bgDarkest,
      'activityBar.dropBackground': `${palette.fgBright}1f`,
      'button.hoverBackground': '#52556c',
      'checkbox.background': palette.bgDarkest,
      'checkbox.border': palette.bgDarkest,
      'checkbox.foreground': palette.fgBright,
      'debugExceptionWidget.background': '#420b0d',
      'debugExceptionWidget.border': '#a31515',

      'debugIcon.breakpointCurrentStackframeForeground': '#ffcc00',
      'debugIcon.breakpointDisabledForeground': palette.neutralGrey2,
      'debugIcon.breakpointForeground': '#e51400',
      'debugIcon.breakpointStackframeForeground': palette.accent7,
      'debugIcon.breakpointUnverifiedForeground': palette.neutralGrey2,
      'debugIcon.continueForeground': palette.accent3,
      'debugIcon.disconnectForeground': '#f48771',
      'debugIcon.pauseForeground': palette.accent3,
      'debugIcon.restartForeground': palette.accent7,
      'debugIcon.startForeground': palette.accent7,
      'debugIcon.stepBackForeground': palette.accent3,
      'debugIcon.stepIntoForeground': palette.accent3,
      'debugIcon.stepOutForeground': palette.accent3,
      'debugIcon.stepOverForeground': palette.accent3,
      'debugIcon.stopForeground': '#f48771',

      descriptionForeground: palette.fgIcon,
      'editor.focusedStackFrameHighlightBackground': '#7abd7a4d',
      'editor.inactiveSelectionBackground': `${palette.bgHighlight}80`,
      'editor.stackFrameHighlightBackground': '#ffff0033',
      'editor.symbolHighlightBackground': `${palette.fgBright}40`,
      'editorActiveLineNumber.foreground': palette.fgIcon,
      'editorBracketMatch.background': '#0064001a',
      'editorBracketMatch.border': '#888888',
      'editorCursor.foreground': '#aeafad',
      'editorGroupHeader.noTabsBackground': palette.bgDark,
      'editorGutter.background': palette.bgDark,
      'editorGutter.commentRangeForeground': palette.fgIcon,
      'editorHint.foreground': '#eeeeeeb3',
      'editorHoverWidget.foreground': palette.fgBright,
      'editorHoverWidget.statusBarBackground': '#303241',
      'editorInfo.foreground': palette.accent3,
      'editorLightBulb.foreground': '#ffcc00',
      'editorLightBulbAutoFix.foreground': palette.accent3,
      'editorLineNumber.activeForeground': palette.fgIcon,
      'editorMarkerNavigationError.background': palette.accent12,
      'editorMarkerNavigationInfo.background': palette.accent3,
      'editorMarkerNavigationWarning.background': palette.accent6,
      'editorOverviewRuler.bracketMatchForeground': '#a0a0a0',
      'editorOverviewRuler.commonContentForeground': '#60606066',
      'editorOverviewRuler.findMatchForeground': '#d186167e',
      'editorOverviewRuler.rangeHighlightForeground': '#007acc99',
      'editorPane.background': palette.bgDark,
      'editorSuggestWidget.border': palette.neutralBorder,
      'editorSuggestWidget.highlightForeground': palette.accent6,
      'editorUnnecessaryCode.opacity': `${palette.neutralBlack}aa`,
      'editorWidget.border': palette.neutralBorder,
      'editorWidget.foreground': palette.fgBright,

      'extensionBadge.remoteBackground': palette.accent2,
      'extensionBadge.remoteForeground': palette.fgBright,

      'gitDecoration.addedResourceForeground': '#81b88b',
      'gitDecoration.submoduleResourceForeground': '#8db9e2',

      'gitlens.gutterBackgroundColor': `${palette.fgBright}13`,
      'gitlens.gutterForegroundColor': '#bebebe',
      'gitlens.gutterUncommittedForegroundColor': '#00bcf299',
      'gitlens.lineHighlightBackgroundColor': '#00bcf233',
      'gitlens.lineHighlightOverviewRulerColor': '#00bcf299',
      'gitlens.trailingLineBackgroundColor': `${palette.neutralBlack}00`,
      'gitlens.trailingLineForegroundColor': '#99999959',

      'icon.foreground': palette.fgIcon,
      'imagePreview.border': '#80808059',
      'inputOption.activeBackground': `${palette.fgMuted}80`,
      'inputValidation.errorBackground': palette.bgError,
      'inputValidation.infoBackground': palette.bgInfo,
      'inputValidation.warningBackground': palette.bgWarning,

      'menu.background': palette.bgDarkest,
      'menu.foreground': palette.fgBright,
      'menu.selectionBackground': palette.bgHighlight,
      'menu.selectionForeground': palette.fgBright,
      'menu.separatorBackground': '#bbbbbb',

      'menubar.selectionBackground': `${palette.fgBright}1a`,
      'menubar.selectionForeground': palette.fgBright,

      'merge.commonContentBackground': '#60606029',
      'merge.commonHeaderBackground': '#60606066',
      'merge.currentContentBackground': `${palette.accent4}3a`,
      'merge.incomingContentBackground': `${palette.accent1}3a`,

      'minimap.errorHighlight': '#ff1212b3',
      'minimap.findMatchHighlight': '#d18616',
      'minimap.selectionHighlight': '#264f78',
      'minimap.warningHighlight': palette.accent6,
      'minimapGutter.addedBackground': '#587c0c',
      'minimapGutter.deletedBackground': '#94151b',
      'minimapGutter.modifiedBackground': '#0c7d9d',
      'notificationCenterHeader.background': palette.bgNotification,
      'notificationLink.foreground': '#3794ff',

      'notifications.background': palette.bgDarkest,
      'notifications.border': palette.bgNotification,
      'notifications.foreground': palette.fgBright,
      'notificationsErrorIcon.foreground': palette.accent12,
      'notificationsInfoIcon.foreground': palette.accent3,
      'notificationsWarningIcon.foreground': palette.accent6,

      'panel.dropBackground': `${palette.fgBright}1f`,
      'peekViewEditorGutter.background': palette.bgDark,
      'problemsErrorIcon.foreground': palette.accent12,
      'problemsInfoIcon.foreground': palette.accent3,
      'problemsWarningIcon.foreground': palette.accent6,
      'quickInput.background': palette.bgDarkest,
      'scrollbar.shadow': palette.neutralBlack,
      'scrollbarSlider.activeBackground': '#bfbfbf66',
      'scrollbarSlider.background': '#79797966',
      'scrollbarSlider.hoverBackground': '#646464b3',
      'searchEditor.findMatchBackground': `${palette.fgBright}2a`,
      'settings.dropdownListBorder': palette.neutralBorder,
      'sideBar.dropBackground': `${palette.fgBright}1f`,

      'statusBarItem.activeBackground': `${palette.fgBright}2e`,
      'statusBarItem.hoverBackground': `${palette.fgBright}1f`,
      'statusBarItem.prominentForeground': palette.fgBright,

      'symbolIcon.arrayForeground': palette.fgBright,
      'symbolIcon.booleanForeground': palette.fgBright,
      'symbolIcon.classForeground': '#ee9d28',
      'symbolIcon.colorForeground': palette.fgBright,
      'symbolIcon.constantForeground': palette.fgBright,
      'symbolIcon.constructorForeground': '#b180d7',
      'symbolIcon.enumeratorForeground': '#ee9d28',
      'symbolIcon.enumeratorMemberForeground': palette.accent3,
      'symbolIcon.eventForeground': '#ee9d28',
      'symbolIcon.fieldForeground': palette.accent3,
      'symbolIcon.fileForeground': palette.fgBright,
      'symbolIcon.folderForeground': palette.fgBright,
      'symbolIcon.functionForeground': '#b180d7',
      'symbolIcon.interfaceForeground': palette.accent3,
      'symbolIcon.keyForeground': palette.fgBright,
      'symbolIcon.keywordForeground': palette.fgBright,
      'symbolIcon.methodForeground': '#b180d7',
      'symbolIcon.moduleForeground': palette.fgBright,
      'symbolIcon.namespaceForeground': palette.fgBright,
      'symbolIcon.nullForeground': palette.fgBright,
      'symbolIcon.numberForeground': palette.fgBright,
      'symbolIcon.objectForeground': palette.fgBright,
      'symbolIcon.operatorForeground': palette.fgBright,
      'symbolIcon.packageForeground': palette.fgBright,
      'symbolIcon.propertyForeground': palette.fgBright,
      'symbolIcon.referenceForeground': palette.fgBright,
      'symbolIcon.snippetForeground': palette.fgBright,
      'symbolIcon.stringForeground': palette.fgBright,
      'symbolIcon.structForeground': palette.fgBright,
      'symbolIcon.textForeground': palette.fgBright,
      'symbolIcon.typeParameterForeground': palette.fgBright,
      'symbolIcon.unitForeground': palette.fgBright,
      'symbolIcon.variableForeground': palette.accent3,

      'tab.activeModifiedBorder': '#3399cc',
      'tab.inactiveModifiedBorder': '#3399cc80',
      'tab.unfocusedActiveBackground': palette.bgDark,
      'tab.unfocusedActiveBorder': `${palette.accent2}40`,
      'tab.unfocusedActiveForeground': `${palette.fgBright}80`,
      'tab.unfocusedActiveModifiedBorder': '#3399cc80',
      'tab.unfocusedInactiveForeground': `${palette.fgMuted}80`,
      'tab.unfocusedInactiveModifiedBorder': '#3399cc40',

      'terminal.border': palette.accent1,
      'terminal.selectionBackground': `${palette.fgBright}40`,
      'textBlockQuote.background': '#7f7f7f1a',
      'textBlockQuote.border': '#007acc80',
      'textCodeBlock.background': '#0a0a0a66',
      'textLink.activeForeground': '#3794ff',
      'textLink.foreground': '#3794ff',
      'textPreformat.foreground': '#d7ba7d',
      'textSeparator.foreground': `${palette.fgBright}2e`,
      'tree.indentGuidesStroke': '#585858',
      'widget.shadow': palette.neutralBlack,
    },
    tokenColors: [
      // --- Estilos de Fonte ---
      { scope: ['emphasis'], settings: { fontStyle: 'italic' } },
      { scope: ['strong'], settings: { fontStyle: 'bold' } },

      // --- Cores Base ---
      { scope: ['header'], settings: { foreground: tokenPalette.operators } },
      { scope: ['source'], settings: { foreground: tokenPalette.foreground } },
      { scope: ['meta.diff', 'meta.diff.header'], settings: { foreground: tokenPalette.comments } },
      { scope: ['markup.inserted'], settings: { foreground: tokenPalette.diffAdded } },
      { scope: ['markup.deleted'], settings: { foreground: tokenPalette.diffDeleted } },
      { scope: ['markup.changed'], settings: { foreground: tokenPalette.diffModified } },
      { scope: ['invalid'], settings: { foreground: tokenPalette.invalid, fontStyle: 'underline italic' } },
      { scope: ['invalid.deprecated'], settings: { foreground: tokenPalette.foreground, fontStyle: 'underline italic' } },
      { scope: ['entity.name.filename'], settings: { foreground: tokenPalette.strings } },
      { scope: ['markup.error'], settings: { foreground: tokenPalette.invalid } },

      // --- Markdown/Prose ---
      { scope: ['markup.underline'], settings: { fontStyle: 'underline' } },
      { scope: ['markup.bold'], settings: { fontStyle: 'bold', foreground: tokenPalette.parameters } },
      { scope: ['markup.heading'], settings: { fontStyle: 'bold', foreground: tokenPalette.operators } },
      { scope: ['markup.italic'], settings: { foreground: tokenPalette.strings, fontStyle: 'italic' } },
      { scope: ['beginning.punctuation.definition.list.markdown', 'beginning.punctuation.definition.quote.markdown', 'punctuation.definition.link.restructuredtext'], settings: { foreground: tokenPalette.classes } },
      { scope: ['markup.inline.raw', 'markup.raw.restructuredtext'], settings: { foreground: tokenPalette.numbers } },
      { scope: ['markup.underline.link', 'markup.underline.link.image'], settings: { foreground: tokenPalette.classes } },
      { scope: ['meta.link.reference.def.restructuredtext', 'punctuation.definition.directive.restructuredtext', 'string.other.link.description', 'string.other.link.title'], settings: { foreground: tokenPalette.keywords } },
      { scope: ['entity.name.directive.restructuredtext', 'markup.quote'], settings: { foreground: tokenPalette.strings, fontStyle: 'italic' } },
      { scope: ['meta.separator.markdown'], settings: { foreground: tokenPalette.comments } },
      { scope: ['fenced_code.block.language', 'markup.raw.inner.restructuredtext', 'markup.fenced_code.block.markdown punctuation.definition.markdown'], settings: { foreground: tokenPalette.numbers } },
      { scope: ['punctuation.definition.constant.restructuredtext'], settings: { foreground: tokenPalette.operators } },
      { scope: ['markup.heading.markdown punctuation.definition.string.begin', 'markup.heading.markdown punctuation.definition.string.end'], settings: { foreground: tokenPalette.operators } },
      { scope: ['meta.paragraph.markdown punctuation.definition.string.begin', 'meta.paragraph.markdown punctuation.definition.string.end'], settings: { foreground: tokenPalette.foreground } },
      { scope: ['markup.quote.markdown meta.paragraph.markdown punctuation.definition.string.begin', 'markup.quote.markdown meta.paragraph.markdown punctuation.definition.string.end'], settings: { foreground: tokenPalette.strings } },

      // --- Classes e 'this' ---
      { scope: ['entity.name.type.class', 'entity.name.class'], settings: { foreground: tokenPalette.classes, fontStyle: 'normal' } },
      { scope: ['keyword.expressions-and-types.swift', 'keyword.other.this', 'variable.language', 'variable.language punctuation.definition.variable.php', 'variable.other.readwrite.instance.ruby', 'variable.parameter.function.language.special'], settings: { foreground: tokenPalette.operators, fontStyle: 'italic' } },
      { scope: ['entity.other.inherited-class'], settings: { fontStyle: 'italic', foreground: tokenPalette.classes } },

      // --- Comentários ---
      { scope: ['comment', 'punctuation.definition.comment', 'unused.comment', 'wildcard.comment'], settings: { foreground: tokenPalette.comments } },
      { scope: ['comment keyword.codetag.notation', 'comment.block.documentation keyword', 'comment.block.documentation storage.type.class'], settings: { foreground: tokenPalette.keywords } },
      { scope: ['comment.block.documentation entity.name.type'], settings: { foreground: tokenPalette.classes, fontStyle: 'italic' } },
      { scope: ['comment.block.documentation entity.name.type punctuation.definition.bracket'], settings: { foreground: tokenPalette.classes } },
      { scope: ['comment.block.documentation variable'], settings: { foreground: tokenPalette.parameters, fontStyle: 'italic' } },

      // --- Constantes e Tags ---
      { scope: ['constant', 'variable.other.constant'], settings: { foreground: tokenPalette.operators } },
      { scope: ['constant.character.escape', 'constant.character.string.escape', 'constant.regexp'], settings: { foreground: tokenPalette.keywords } },
      { scope: ['entity.name.tag'], settings: { foreground: tokenPalette.tags } },
      { scope: ['entity.other.attribute-name.parent-selector'], settings: { foreground: tokenPalette.tags } },
      { scope: ['entity.other.attribute-name'], settings: { foreground: tokenPalette.attributes, fontStyle: 'italic' } },

      // --- Funções e Parâmetros ---
      { scope: ['entity.name.function', 'meta.function-call.generic', 'meta.function-call.object', 'meta.function-call.php', 'meta.function-call.static', 'meta.method-call.java meta.method', 'meta.method.groovy', 'support.function.any-method.lua', 'keyword.operator.function.infix'], settings: { foreground: tokenPalette.functions } },
      { scope: ['entity.name.variable.parameter', 'meta.at-rule.function variable', 'meta.at-rule.mixin variable', 'meta.function.arguments variable.other.php', 'meta.selectionset.graphql meta.arguments.graphql variable.arguments.graphql', 'variable.parameter'], settings: { fontStyle: 'italic', foreground: tokenPalette.parameters } },
      { scope: ['meta.decorator variable.other.readwrite', 'meta.decorator variable.other.property'], settings: { foreground: tokenPalette.functions, fontStyle: 'italic' } },
      { scope: ['meta.decorator variable.other.object'], settings: { foreground: tokenPalette.functions } },

      // --- Palavras-chave (Keywords) e Storage ---
      { scope: ['keyword', 'punctuation.definition.keyword'], settings: { foreground: tokenPalette.keywords } },
      { scope: ['keyword.control.new', 'keyword.operator.new'], settings: { fontStyle: 'bold' } },
      { scope: ['meta.selector'], settings: { foreground: tokenPalette.keywords } },
      { scope: ['support'], settings: { fontStyle: 'italic', foreground: tokenPalette.classes } },
      { scope: ['support.function.magic', 'support.variable', 'variable.other.predefined'], settings: { fontStyle: 'regular', foreground: tokenPalette.operators } },
      { scope: ['support.function', 'support.type.property-name'], settings: { fontStyle: 'regular' } },

      // --- Separadores e Pontuação ---
      { scope: ['constant.other.symbol.hashkey punctuation.definition.constant.ruby', 'entity.other.attribute-name.placeholder punctuation', 'entity.other.attribute-name.pseudo-class punctuation', 'entity.other.attribute-name.pseudo-element punctuation', 'meta.group.double.toml', 'meta.group.toml', 'meta.object-binding-pattern-variable punctuation.destructuring', 'punctuation.colon.graphql', 'punctuation.definition.block.scalar.folded.yaml', 'punctuation.definition.block.scalar.literal.yaml', 'punctuation.definition.block.sequence.item.yaml', 'punctuation.definition.entity.other.inherited-class', 'punctuation.function.swift', 'punctuation.separator.dictionary.key-value', 'punctuation.separator.hash', 'punctuation.separator.inheritance', 'punctuation.separator.key-value', 'punctuation.separator.key-value.mapping.yaml', 'punctuation.separator.namespace', 'punctuation.separator.pointer-access', 'punctuation.separator.slice', 'string.unquoted.heredoc punctuation.definition.string', 'support.other.chomping-indicator.yaml', 'punctuation.separator.annotation'], settings: { foreground: tokenPalette.keywords } },
      { scope: ['keyword.operator.other.powershell', 'keyword.other.statement-separator.powershell', 'meta.brace.round', 'meta.function-call punctuation', 'punctuation.definition.arguments.begin', 'punctuation.definition.arguments.end', 'punctuation.definition.entity.begin', 'punctuation.definition.entity.end', 'punctuation.definition.tag.cs', 'punctuation.definition.type.begin', 'punctuation.definition.type.end', 'punctuation.section.scope.begin', 'punctuation.section.scope.end', 'storage.type.generic.java', 'string.template meta.brace', 'string.template punctuation.accessor'], settings: { foreground: tokenPalette.foreground } },

      // --- Interpolação ---
      { scope: ['meta.string-contents.quoted.double punctuation.definition.variable', 'punctuation.definition.interpolation.begin', 'punctuation.definition.interpolation.end', 'punctuation.definition.template-expression.begin', 'punctuation.definition.template-expression.end', 'punctuation.section.embedded.begin', 'punctuation.section.embedded.coffee', 'punctuation.section.embedded.end', 'punctuation.section.embedded.end source.php', 'punctuation.section.embedded.end source.ruby', 'punctuation.definition.variable.makefile'], settings: { foreground: tokenPalette.keywords } },

      // --- JSON/YAML/TOML Keys ---
      { scope: ['entity.name.function.target.makefile', 'entity.name.section.toml', 'entity.name.tag.yaml', 'variable.other.key.toml'], settings: { foreground: tokenPalette.classes } },
      { scope: ['constant.other.date', 'constant.other.timestamp'], settings: { foreground: tokenPalette.parameters } },
      { scope: ['variable.other.alias.yaml'], settings: { fontStyle: 'italic underline', foreground: tokenPalette.functions } },

      // --- Storage e Tipos ---
      { scope: ['storage', 'meta.implementation storage.type.objc', 'meta.interface-or-protocol storage.type.objc', 'source.groovy storage.type.def'], settings: { fontStyle: 'regular', foreground: tokenPalette.keywords } },
      { scope: ['entity.name.type', 'keyword.primitive-datatypes.swift', 'keyword.type.cs', 'meta.protocol-list.objc', 'meta.return-type.objc', 'source.go storage.type', 'source.groovy storage.type', 'source.java storage.type', 'source.powershell entity.other.attribute-name', 'storage.class.std.rust', 'storage.type.attribute.swift', 'storage.type.c', 'storage.type.core.rust', 'storage.type.cs', 'storage.type.groovy', 'storage.type.objc', 'storage.type.php', 'storage.type.haskell', 'storage.type.ocaml'], settings: { fontStyle: 'italic', foreground: tokenPalette.types } },
      { scope: ['entity.name.type.type-parameter', 'meta.indexer.mappedtype.declaration entity.name.type', 'meta.type.parameters entity.name.type'], settings: { foreground: tokenPalette.parameters } },
      { scope: ['storage.modifier'], settings: { foreground: tokenPalette.keywords } },

      // --- RegExp ---
      { scope: ['string.regexp', 'constant.other.character-class.set.regexp', 'constant.character.escape.backslash.regexp'], settings: { foreground: tokenPalette.strings } },
      { scope: ['punctuation.definition.group.capture.regexp'], settings: { foreground: tokenPalette.keywords } },
      { scope: ['string.regexp punctuation.definition.string.begin', 'string.regexp punctuation.definition.string.end'], settings: { foreground: tokenPalette.invalid } },
      { scope: ['punctuation.definition.character-class.regexp'], settings: { foreground: tokenPalette.classes } },
      { scope: ['punctuation.definition.group.regexp'], settings: { foreground: tokenPalette.parameters } },
      { scope: ['punctuation.definition.group.assertion.regexp', 'keyword.operator.negation.regexp'], settings: { foreground: tokenPalette.invalid } },
      { scope: ['meta.assertion.look-ahead.regexp'], settings: { foreground: tokenPalette.numbers } },

      // --- Strings ---
      { scope: ['string'], settings: { foreground: tokenPalette.strings } },
      { scope: ['punctuation.definition.string.begin', 'punctuation.definition.string.end'], settings: { foreground: tokenPalette.strings } },
      { scope: ['punctuation.support.type.property-name.begin', 'punctuation.support.type.property-name.end'], settings: { foreground: tokenPalette.strings } },
      { scope: ['string.quoted.docstring.multi', 'string.quoted.docstring.multi.python punctuation.definition.string.begin', 'string.quoted.docstring.multi.python punctuation.definition.string.end', 'string.quoted.docstring.multi.python constant.character.escape'], settings: { foreground: tokenPalette.comments } },

      // --- Variáveis e Propriedades ---
      { scope: ['variable', 'constant.other.key.perl', 'support.variable.property', 'variable.other.constant.js', 'variable.other.constant.ts', 'variable.other.constant.tsx'], settings: { foreground: tokenPalette.variables } },
      { scope: ['meta.import variable.other.readwrite', 'meta.object-binding-pattern-variable variable.object.property', 'meta.variable.assignment.destructured.object.coffee variable'], settings: { fontStyle: 'italic', foreground: tokenPalette.parameters } },
      { scope: ['meta.import variable.other.readwrite.alias', 'meta.export variable.other.readwrite.alias', 'meta.variable.assignment.destructured.object.coffee variable variable'], settings: { fontStyle: 'normal', foreground: tokenPalette.variables } },

      // --- GraphQL ---
      { scope: ['meta.selectionset.graphql variable'], settings: { foreground: tokenPalette.strings } },
      { scope: ['meta.selectionset.graphql meta.arguments variable'], settings: { foreground: tokenPalette.foreground } },
      { scope: ['entity.name.fragment.graphql', 'variable.fragment.graphql'], settings: { foreground: tokenPalette.classes } },

      // --- Edge Cases (Resets) ---
      { scope: ['constant.other.symbol.hashkey.ruby', 'keyword.operator.dereference.java', 'keyword.operator.navigation.groovy', 'meta.scope.for-loop.shell punctuation.definition.string.begin', 'meta.scope.for-loop.shell punctuation.definition.string.end', 'meta.scope.for-loop.shell string', 'storage.modifier.import', 'punctuation.section.embedded.begin.tsx', 'punctuation.section.embedded.end.tsx', 'punctuation.section.embedded.begin.jsx', 'punctuation.section.embedded.end.jsx', 'punctuation.separator.list.comma.css', 'constant.language.empty-list.haskell'], settings: { foreground: tokenPalette.foreground } },
      { scope: ['source.shell variable.other'], settings: { foreground: tokenPalette.operators } },
      { scope: ['support.constant'], settings: { fontStyle: 'normal', foreground: tokenPalette.operators } },
      { scope: ['meta.scope.prerequisites.makefile'], settings: { foreground: tokenPalette.strings } },
      { scope: ['meta.attribute-selector.scss'], settings: { foreground: tokenPalette.strings } },
      { scope: ['punctuation.definition.attribute-selector.end.bracket.square.scss', 'punctuation.definition.attribute-selector.begin.bracket.square.scss'], settings: { foreground: tokenPalette.foreground } },
      { scope: ['meta.preprocessor.haskell'], settings: { foreground: tokenPalette.comments } },

      // --- Tokens de Log (Info, Warn, etc.) ---
      { scope: 'token.info-token', settings: { foreground: '#6796e6' } },
      { scope: 'token.warn-token', settings: { foreground: '#cd9731' } },
      { scope: 'token.error-token', settings: { foreground: '#f44747' } },
      { scope: 'token.debug-token', settings: { foreground: '#b267e6' } },
    ],
  };
};

export default baseColors;
